#!/usr/bin/env python3
"""Validate Alembic-style migration revision and ownership hygiene.

Runtime-independent source-study tooling. It parses migration Python with the
standard library only and never imports the inspected application.
"""
from __future__ import annotations

import argparse
import ast
import json
from dataclasses import asdict, dataclass
from pathlib import Path


@dataclass(frozen=True, slots=True)
class Migration:
    path: str
    revision: str | None
    down_revision: tuple[str, ...]
    branch_labels: tuple[str, ...]
    depends_on: tuple[str, ...]
    logical_objects: tuple[str, ...]
    parse_status: str
    notes: tuple[str, ...]


def _literal(node: ast.AST | None) -> str | None:
    if isinstance(node, ast.Constant) and isinstance(node.value, str):
        return node.value
    return None


def _strings(node: ast.AST | None) -> tuple[str, ...]:
    if node is None:
        return ()
    if isinstance(node, (ast.Tuple, ast.List, ast.Set)):
        return tuple(sorted(v for v in (_literal(item) for item in node.elts) if v))
    value = _literal(node)
    return (value,) if value else ()


def _logical_objects(tree: ast.AST) -> tuple[str, ...]:
    objects: set[str] = set()
    methods = {
        "create_table", "drop_table", "add_column", "drop_column",
        "create_index", "drop_index", "create_foreign_key", "drop_constraint",
    }
    for node in ast.walk(tree):
        if not isinstance(node, ast.Call) or not isinstance(node.func, ast.Attribute):
            continue
        method = node.func.attr
        if method not in methods:
            continue
        values: list[str] = []
        for arg in node.args[:2]:
            value = _literal(arg)
            if value:
                values.append(value)
        for keyword in node.keywords:
            if keyword.arg in {"table_name", "column_name", "index_name", "constraint_name"}:
                value = _literal(keyword.value)
                if value:
                    values.append(value)
        if values:
            objects.add(f"{method}:{':'.join(values)}")
    return tuple(sorted(objects))


def parse_file(path: Path, root: Path) -> Migration:
    relative = path.relative_to(root).as_posix()
    try:
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    except (OSError, UnicodeDecodeError, SyntaxError) as exc:
        return Migration(relative, None, (), (), (), (), "ERROR", (f"parse/read failure: {exc}",))
    values: dict[str, ast.AST | None] = {}
    for node in tree.body:
        if isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name) and target.id in {"revision", "down_revision", "branch_labels", "depends_on"}:
                    values[target.id] = node.value
    notes: list[str] = []
    revision = _literal(values.get("revision"))
    if not revision:
        notes.append("missing static revision")
    if "autogenerated" in path.name.lower():
        notes.append("autogenerated-name; review original migration ownership")
    return Migration(
        relative,
        revision,
        _strings(values.get("down_revision")),
        _strings(values.get("branch_labels")),
        _strings(values.get("depends_on")),
        _logical_objects(tree),
        "OK" if revision else "ERROR",
        tuple(notes),
    )


def scan(root: Path) -> list[Migration]:
    files = sorted(
        path
        for path in root.rglob("*.py")
        if path.is_file()
        and path.name != "__init__.py"
        and not any(part in {".git", ".venv", "venv", "__pycache__"} for part in path.parts)
    )
    return [parse_file(path, root) for path in files]


def validate(migrations: list[Migration]) -> tuple[list[str], list[str]]:
    errors: list[str] = []
    warnings: list[str] = []
    for item in migrations:
        if item.parse_status == "ERROR":
            errors.append(f"invalid migration metadata {item.path}: {', '.join(item.notes) or 'parse failure'}")
    usable = [item for item in migrations if item.parse_status == "OK" and item.revision]
    revisions: dict[str, list[Migration]] = {}
    for item in usable:
        revisions.setdefault(item.revision or "", []).append(item)
    for revision, items in sorted(revisions.items()):
        if len(items) > 1:
            errors.append(f"duplicate revision {revision}: {', '.join(item.path for item in items)}")
    known = set(revisions)
    for item in usable:
        for parent in item.down_revision:
            if parent and parent not in known:
                errors.append(f"missing down_revision {parent} referenced by {item.path}")
        for dependency in item.depends_on:
            if dependency and dependency not in known:
                errors.append(f"missing depends_on {dependency} referenced by {item.path}")
    object_owners: dict[str, list[Migration]] = {}
    for item in usable:
        for logical_object in item.logical_objects:
            object_owners.setdefault(logical_object, []).append(item)
    for logical_object, owners in sorted(object_owners.items()):
        if len(owners) > 1:
            paths = ", ".join(item.path for item in owners)
            warnings.append(f"logical object touched by multiple migrations; review whether evolution is intentional: {logical_object}: {paths}")
    return errors, warnings


def payload(root: Path) -> dict[str, object]:
    migrations = scan(root)
    errors, warnings = validate(migrations)
    return {
        "schema_version": 1,
        "source_root": str(root),
        "migration_count": len(migrations),
        "migrations": [asdict(item) for item in migrations],
        "errors": errors,
        "warnings": warnings,
        "closure_rule": "static migration validation does not prove execution, live-schema state, rollback safety, or production ownership",
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--migrations-root", type=Path, required=True)
    parser.add_argument("--format", choices=("json", "markdown"), default="json")
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    root = args.migrations_root.resolve()
    if not root.is_dir():
        raise SystemExit(f"migration root is not a directory: {root}")
    data = payload(root)
    if args.format == "json":
        text = json.dumps(data, indent=2, sort_keys=True) + "\n"
    else:
        lines = ["# Migration Graph Evidence", "", f"Migration count: `{data['migration_count']}`", "", "| Path | Revision | Parents | Dependencies | Objects | Status |", "|---|---|---|---|---|---|"]
        for item in data["migrations"]:  # type: ignore[union-attr]
            lines.append(f"| `{item['path']}` | `{item['revision'] or ''}` | `{','.join(item['down_revision'])}` | `{','.join(item['depends_on'])}` | `{','.join(item['logical_objects'])}` | `{item['parse_status']}` |")
        lines += ["", "## Errors", ""]
        lines.extend(f"- {error}" for error in data["errors"])  # type: ignore[arg-type]
        lines += ["", "## Warnings", ""]
        lines.extend(f"- {warning}" for warning in data["warnings"])  # type: ignore[arg-type]
        lines += ["", "Static graph validation is not production schema verification.", ""]
        text = "\n".join(lines)
    if args.output:
        args.output.write_text(text, encoding="utf-8")
    else:
        print(text, end="")
    return 1 if data["errors"] else 0


if __name__ == "__main__":
    raise SystemExit(main())
